# Generated by Django 5.0 on 2025-12-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_leaverequest_payment'),
        ('authentication', '0013_add_payment_slip_upload_fields'),
    ]

    operations = [
    ]
