import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/api_service.dart';
import '../models/payment_slip_model.dart';

class PaymentSlipsScreen extends StatefulWidget {
  const PaymentSlipsScreen({super.key});

  @override
  State<PaymentSlipsScreen> createState() => _PaymentSlipsScreenState();
}

class _PaymentSlipsScreenState extends State<PaymentSlipsScreen> {
  List<PaymentSlip> _paymentSlips = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadPaymentSlips();
  }

  Future<void> _loadPaymentSlips() async {
    setState(() => _isLoading = true);

    try {
      final result = await ApiService.getMyPaymentSlips();

      if (mounted) {
        setState(() {
          _isLoading = false;
          if (result['success']) {
            final data = result['data'];
            try {
              if (data is List) {
                _paymentSlips = data.map((json) {
                  try {
                    return PaymentSlip.fromJson(json as Map<String, dynamic>);
                  } catch (e) {
                    print('Error parsing payment slip item: $e');
                    print('Item data: $json');
                    rethrow;
                  }
                }).toList();
              } else if (data is Map && data.containsKey('results')) {
                _paymentSlips = (data['results'] as List)
                    .map((json) {
                      try {
                        return PaymentSlip.fromJson(json as Map<String, dynamic>);
                      } catch (e) {
                        print('Error parsing payment slip item: $e');
                        print('Item data: $json');
                        rethrow;
                      }
                    })
                    .toList();
              } else {
                // Handle case where data might be directly a list
                _paymentSlips = [];
              }
            } catch (e) {
              print('Error processing payment slips data: $e');
              _paymentSlips = [];
              rethrow;
            }
          } else {
            _paymentSlips = [];
            // Show error message if needed
            if (result['message'] != null) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(result['message']),
                  backgroundColor: Colors.orange,
                ),
              );
            }
          }
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _paymentSlips = [];
        });
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error loading payment slips: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Payment Slips'),
        centerTitle: true,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _paymentSlips.isEmpty
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.payment, size: 64, color: Colors.grey[400]),
                      const SizedBox(height: 16),
                      Text(
                        'No payment slips found',
                        style: TextStyle(
                          fontSize: 18,
                          color: Colors.grey[600],
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Payment slips will appear here once generated by admin',
                        style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[500],
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                )
              : RefreshIndicator(
                  onRefresh: _loadPaymentSlips,
                  child: ListView.builder(
                    padding: const EdgeInsets.all(16.0),
                    itemCount: _paymentSlips.length,
                    itemBuilder: (context, index) {
                      final slip = _paymentSlips[index];
                      return Card(
                        elevation: 4,
                        margin: const EdgeInsets.only(bottom: 16),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: ExpansionTile(
                          tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                          leading: CircleAvatar(
                            radius: 20,
                            backgroundColor: _getStatusColor(slip.status),
                            child: Icon(
                              _getStatusIcon(slip.status),
                              color: Colors.white,
                              size: 20,
                            ),
                          ),
                          title: Text(
                            '${slip.monthDisplay} ${slip.year}',
                            style: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 16,
                            ),
                          ),
                          subtitle: Padding(
                            padding: const EdgeInsets.only(top: 4.0),
                            child: Text(
                              'Role: ${slip.roleDisplay}',
                              style: TextStyle(
                                color: Colors.grey[600],
                                fontSize: 13,
                              ),
                            ),
                          ),
                          trailing: SizedBox(
                            width: 110,
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.end,
                              children: [
                                Text(
                                  'Rs. ${NumberFormat('#,##,###').format(slip.netSalary)}',
                                  style: TextStyle(
                                    fontSize: 15,
                                    fontWeight: FontWeight.bold,
                                    color: Colors.green[700],
                                  ),
                                  textAlign: TextAlign.right,
                                  overflow: TextOverflow.ellipsis,
                                  maxLines: 1,
                                ),
                                const SizedBox(height: 4),
                                Chip(
                                  label: Padding(
                                    padding: const EdgeInsets.symmetric(horizontal: 4),
                                    child: Text(
                                      slip.statusDisplay,
                                      style: const TextStyle(
                                        fontSize: 10,
                                        color: Colors.white,
                                        height: 1.2,
                                      ),
                                      maxLines: 1,
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ),
                                  backgroundColor: _getStatusColor(slip.status),
                                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                  visualDensity: VisualDensity.compact,
                                  padding: EdgeInsets.zero,
                                ),
                              ],
                            ),
                          ),
                          children: [
                            ConstrainedBox(
                              constraints: BoxConstraints(
                                maxHeight: MediaQuery.of(context).size.height * 0.7,
                              ),
                              child: SingleChildScrollView(
                                child: _buildPaymentSlipContent(slip),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
    );
  }

  Widget _buildPaymentSlipContent(PaymentSlip slip) {
    return Container(
      constraints: const BoxConstraints(),
      padding: const EdgeInsets.all(20.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Company Header
          Container(
            padding: const EdgeInsets.all(20.0),
            decoration: BoxDecoration(
              color: Colors.blue[50],
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.blue[200]!),
            ),
            child: Column(
              children: [
                // Company Logo (Same as login screen)
                const Icon(
                  Icons.verified_user,
                  size: 60,
                  color: Colors.blue,
                ),
                const SizedBox(height: 12),
                // Company Name (Same as login screen)
                const Text(
                  'Auditra',
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: Colors.blue,
                  ),
                ),
                const SizedBox(height: 4),
                const Text(
                  'Payment Slip',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w500,
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),
          
          // Employee Information Section
          Container(
            padding: const EdgeInsets.all(16.0),
            decoration: BoxDecoration(
              color: Colors.grey[50],
              borderRadius: BorderRadius.circular(8),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildInfoRow('Employee Name', slip.userFullName, isBold: true),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Expanded(
                      child: _buildInfoRow('Payment Month', slip.monthDisplay),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _buildInfoRow('Year', slip.year.toString()),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Expanded(
                      child: _buildInfoRow(
                        'Pay Slip Number',
                        slip.paySlipNumber ?? 'N/A',
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: _buildInfoRow(
                        'Employee Number',
                        slip.employeeNumber ?? 'N/A',
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),
          
          // Salary Breakdown Section
          Container(
            padding: const EdgeInsets.all(16.0),
            decoration: BoxDecoration(
              color: Colors.grey[50],
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.grey[300]!),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Text(
                  'Salary Breakdown',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.black87,
                  ),
                ),
                const SizedBox(height: 16),
                // Basic Salary
                _buildSalaryRow('Basic Salary', slip.salary, Colors.blue),
                const SizedBox(height: 12),
                // Allowances
                _buildSalaryRow('Allowances', slip.allowances, Colors.orange),
                const SizedBox(height: 12),
                // Overtime Hours and Pay
                if (slip.overtimeHours > 0) ...[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Overtime Hours:',
                        style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[700],
                        ),
                      ),
                      Text(
                        '${slip.overtimeHours.toStringAsFixed(1)} hrs',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                          color: Colors.grey[800],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  _buildSalaryRow('Overtime Pay', slip.overtimePay, Colors.purple),
                  const SizedBox(height: 12),
                ],
                const Divider(),
                const SizedBox(height: 12),
                // EPF Deduction
                _buildSalaryRow('EPF Contribution (8%)', -slip.epfContribution, Colors.red, isDeduction: true),
                const SizedBox(height: 16),
                // Net Salary
                Container(
                  padding: const EdgeInsets.all(12.0),
                  decoration: BoxDecoration(
                    color: Colors.green[50],
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.green[200]!),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Net Salary:',
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: Colors.black87,
                        ),
                      ),
                      Text(
                        'Rs. ${NumberFormat('#,##,###').format(slip.netSalary)}',
                        style: TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Colors.green[700],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),
          
          // Additional Details
          const Divider(),
          const SizedBox(height: 12),
          _buildDetailRow('Role', slip.roleDisplay),
          _buildDetailRow('Status', slip.statusDisplay),
          _buildDetailRow(
            'Generated At',
            DateFormat('MMM dd, yyyy HH:mm').format(slip.generatedAt),
          ),
          if (slip.generatedByUsername != null)
            _buildDetailRow(
              'Generated By',
              slip.generatedByUsername!,
            ),
          if (slip.paidAt != null)
            _buildDetailRow(
              'Paid At',
              DateFormat('MMM dd, yyyy HH:mm').format(slip.paidAt!),
            ),
        ],
      ),
    );
  }

  Widget _buildInfoRow(String label, String value, {bool isBold = false}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 12,
            color: Colors.grey[600],
            fontWeight: FontWeight.w500,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          value,
          style: TextStyle(
            fontSize: 16,
            fontWeight: isBold ? FontWeight.bold : FontWeight.normal,
            color: Colors.black87,
          ),
        ),
      ],
    );
  }

  Widget _buildDetailRow(String label, String value, {bool isHighlight = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 120,
            child: Text(
              label,
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
                fontSize: 14,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: TextStyle(
                fontSize: isHighlight ? 16 : 14,
                fontWeight: isHighlight ? FontWeight.bold : FontWeight.normal,
                color: isHighlight ? Colors.green[700] : Colors.black87,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSalaryRow(String label, double amount, Color color, {bool isDeduction = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14,
            color: Colors.grey[700],
            fontWeight: FontWeight.w500,
          ),
        ),
        Text(
          '${isDeduction ? '-' : '+'}Rs. ${NumberFormat('#,##,###').format(amount.abs())}',
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            color: isDeduction ? Colors.red[700] : color,
          ),
        ),
      ],
    );
  }

  Color _getStatusColor(String status) {
    switch (status) {
      case 'paid':
        return Colors.green;
      case 'generated':
        return Colors.blue;
      case 'pending':
        return Colors.orange;
      default:
        return Colors.grey;
    }
  }

  IconData _getStatusIcon(String status) {
    switch (status) {
      case 'paid':
        return Icons.check_circle;
      case 'generated':
        return Icons.description;
      case 'pending':
        return Icons.pending;
      default:
        return Icons.help_outline;
    }
  }
}

