# Generated by Django 5.0 on 2025-12-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_projectdeleterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: Link message to a project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='chat_chatme_sender__fc7d7a_idx'), models.Index(fields=['recipient', 'created_at'], name='chat_chatme_recipie_d65f98_idx'), models.Index(fields=['project', 'created_at'], name='chat_chatme_project_980edb_idx')],
            },
        ),
    ]
